name: CMake Test 01

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - feature/*
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CMAKE_VERSION: 3.22.1
  BUILD_TYPE: Release

jobs:
  my_first_job:
    name: My first job
    runs-on: windows-latest
    steps:
      - name: first step of first job
        shell: bash
        run: echo $PATH

         
 